name: flavor_example
description: A new Flutter application.
version: 1.0.0+1
environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  simple_logger: any
  package_info: any
  firebase_auth: any
  cloud_firestore: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.0"
flutter:
  uses-material-design: true
flutter_icons:
  image_path: "assets/images/icon.png"
  android: true
  ios: true
#  adaptive_icon_background:
#  adaptive_icon_foreground:
