name: flavor_example
description: A new Flutter application.
version: 1.0.0+1
environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  simple_logger: any
  package_info: any
  firebase_auth: any
  cloud_firestore: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:
    git:
      url: git://github.com/sestegra/flutter_launcher_icons.git
      ref: flavors
flutter:
  uses-material-design: true
